#---
# - hosts: "all"
#   tasks:
#   - name: "check server status"
#     ansible.builtin.ping:

#   - name: "copy file from  /etc/nginx/conf.d  to  /Desktop"
#     ansible.builtin.copy:
#       src: /etc/nginx/conf.d/nextcloud.conf
#       dest: /home/pd6/Desktop/nextcloud.conf
#       remote_src: yes

#   - name: "edit string"
#     ansible.builtin.lineinfile:
#       path: /home/pd6/Desktop/nextcloud.conf
#       search_string: 'server_name nextcloud.pd16.com;'
#       line: server_name nextcloud.local.com;
#   узнать, как вставить пробелы перед 4 строкой




#________local test on my pc_______
---
- hosts: "all"
  tasks:
  - name: "check server status"
    ansible.builtin.ping:

  - name: "edit string"
    ansible.builtin.command: sed -i "s/server_name nextcloud.pd16.com;/server_name nextcloud.local.com;/" /home/niko/Desktop/nextcloud.conf 
    register: result

  # - name: "Debug"
  #   ansible.builtin.debug:
  #     msg: "nextcloud.conf ---> {{ result }}"